// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// prediction_curve_max_dev_weighted_cpp
Rcpp::NumericMatrix prediction_curve_max_dev_weighted_cpp(const Rcpp::NumericMatrix data, const Rcpp::NumericMatrix boot_weights, const double ridge);
RcppExport SEXP _funbootband_prediction_curve_max_dev_weighted_cpp(SEXP dataSEXP, SEXP boot_weightsSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type boot_weights(boot_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(prediction_curve_max_dev_weighted_cpp(data, boot_weights, ridge));
    return rcpp_result_gen;
END_RCPP
}
// confidence_max_dev_studentized_cpp
Rcpp::NumericVector confidence_max_dev_studentized_cpp(const Rcpp::NumericMatrix unit_data, const Rcpp::NumericVector mu_hat, const Rcpp::NumericMatrix boot_weights, const double ridge);
RcppExport SEXP _funbootband_confidence_max_dev_studentized_cpp(SEXP unit_dataSEXP, SEXP mu_hatSEXP, SEXP boot_weightsSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type unit_data(unit_dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type mu_hat(mu_hatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type boot_weights(boot_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(confidence_max_dev_studentized_cpp(unit_data, mu_hat, boot_weights, ridge));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_funbootband_prediction_curve_max_dev_weighted_cpp", (DL_FUNC) &_funbootband_prediction_curve_max_dev_weighted_cpp, 3},
    {"_funbootband_confidence_max_dev_studentized_cpp", (DL_FUNC) &_funbootband_confidence_max_dev_studentized_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_funbootband(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
