# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prediction_curve_max_dev_weighted_cpp <- function(data, boot_weights, ridge = 1e-12) {
    .Call(`_funbootband_prediction_curve_max_dev_weighted_cpp`, data, boot_weights, ridge)
}

confidence_max_dev_studentized_cpp <- function(unit_data, mu_hat, boot_weights, ridge = 1e-12) {
    .Call(`_funbootband_confidence_max_dev_studentized_cpp`, unit_data, mu_hat, boot_weights, ridge)
}

