# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prediction_max_dev_cpp <- function(resid_mat, mu_hat, sd_hat, idx_mat) {
    .Call(`_funbootband_prediction_max_dev_cpp`, resid_mat, mu_hat, sd_hat, idx_mat)
}

confidence_max_dev_cpp <- function(data, mu_hat, se_hat, idx_mat) {
    .Call(`_funbootband_confidence_max_dev_cpp`, data, mu_hat, se_hat, idx_mat)
}

